"""Machine verification of the collapse-bridge identity (Proposition B).

The manuscript uses three statistics that the word "collapse" could
conflate: retrospective conditioning (specific information), prospective
entropy contraction of the future-basin distribution, and interventional
divergence between do-laws. Proposition B states when they coincide.

Setting: at a declared step t, the system chooses action A ~ pi(.|s_t);
the future basin B = g(tau_{>t}) is generated by a FIXED rollout law after
the action (no unobserved confounding: in an MDP, choosing a and do(a)
induce the same future law). Then:

    (i)  action-attributable prospective contraction equals the
         action--future mutual information:
             H(P_t(B)) - E_{a~pi}[ H(P(B | do(a))) ] = I(A; B);
    (ii) the same quantity is the pi-average interventional divergence:
             I(A; B) = E_{a~pi}[ KL( P(B | do(a)) || P_t(B) ) ];
    (iii) it is also the expected retrospective update about the action:
             I(A; B) = E_{b}[ KL( pi(A | B=b) || pi(A) ) ];
    (iv) degenerate boundary: if pi is deterministic, I(A; B) = 0 --
         any remaining contraction is exogenous noise revelation, which
         is why ordinary greedy decisions carry no action-attributable
         collapse and why potential requires an open action distribution.

(i)-(iii) are standard mutual-information identities once the do-law
equals the conditional law (the MDP no-confounding condition); the
scientific content is the DECLARATION that all manuscript measurements
target the interventional form (ii), with (iii) as bookkeeping and (i)
as the entropy-contraction reading. This script verifies the identities
to machine precision on 10,000 random finite systems plus the
deterministic boundary case, and on trained-policy trigger steps of the
contextual sacrifice gridworld.
"""

from __future__ import annotations

import json
import math
import random
from pathlib import Path
from typing import Dict, List

import numpy as np

OUTPUTS = Path(__file__).resolve().parent / "outputs"


def entropy(p: np.ndarray) -> float:
    p = p[p > 0]
    return float(-(p * np.log2(p)).sum())


def kl(p: np.ndarray, q: np.ndarray) -> float:
    mask = p > 0
    return float((p[mask] * np.log2(p[mask] / q[mask])).sum())


def random_system(rng: np.random.Generator, n_actions: int,
                  n_basins: int, deterministic: bool = False):
    if deterministic:
        pi = np.zeros(n_actions)
        pi[rng.integers(n_actions)] = 1.0
    else:
        pi = rng.dirichlet(np.ones(n_actions))
    do_laws = rng.dirichlet(np.ones(n_basins), size=n_actions)
    return pi, do_laws


def check_identities(pi: np.ndarray, do_laws: np.ndarray) -> Dict[str, float]:
    marginal = pi @ do_laws                       # P_t(B)
    joint = pi[:, None] * do_laws                 # P(A, B)
    # (i) contraction form
    contraction = entropy(marginal) - sum(
        pi[a] * entropy(do_laws[a]) for a in range(len(pi)))
    # (ii) interventional form
    interventional = sum(
        pi[a] * kl(do_laws[a], marginal) for a in range(len(pi))
        if pi[a] > 0)
    # (iii) retrospective form
    retro = 0.0
    for b in range(do_laws.shape[1]):
        pb = marginal[b]
        if pb <= 0:
            continue
        posterior = joint[:, b] / pb
        mask = posterior > 0
        retro += pb * float(
            (posterior[mask] * np.log2(posterior[mask] / pi[mask])).sum())
    return {
        "contraction": contraction,
        "interventional": interventional,
        "retrospective": retro,
    }


def gridworld_case() -> Dict[str, float]:
    """Trigger-step check on a trained policy of the benchmark."""
    from contextual_sacrifice_gridworld import (
        ContextualSacrificeEnv, JOINT_ACTIONS, classify_basin,
        train_policy, q_values)
    q_table = train_policy("uncertain_preference", 20_000, 424242)
    env = ContextualSacrificeEnv("rescue")
    state = env.reset()
    values = q_values(q_table, state, "latent_sacrifice")
    temps = np.array([values[a] for a in JOINT_ACTIONS]) / 0.9
    temps -= temps.max()
    pi = np.exp(temps) / np.exp(temps).sum()

    rng = random.Random(7)
    basins = ("sacrifice_rescue", "team_direct", "selfish_escape",
              "failed_noise")
    do_laws = []
    for action in JOINT_ACTIONS:
        counts = {b: 0 for b in basins}
        for _ in range(400):
            env2 = ContextualSacrificeEnv("rescue")
            s = env2.reset()
            result = env2.step(s, action)
            events = list(result.events)
            s = result.state
            done = result.done
            while not done:
                vals = q_values(q_table, s, "latent_sacrifice")
                acts = list(JOINT_ACTIONS)
                mx = max(vals[a] for a in acts)
                ws = [math.exp((vals[a] - mx) / 0.9) for a in acts]
                tot = sum(ws)
                u = rng.random() * tot
                acc = 0.0
                for a, w in zip(acts, ws):
                    acc += w
                    if u <= acc:
                        chosen = a
                        break
                result = env2.step(s, chosen)
                events.extend(result.events)
                s = result.state
                done = result.done
            counts[classify_basin(events)] += 1
        do_laws.append(np.array([counts[b] / 400 for b in basins]))
    return check_identities(pi, np.vstack(do_laws))


def main() -> None:
    rng = np.random.default_rng(20260718)
    max_gap = 0.0
    for _ in range(10_000):
        pi, do_laws = random_system(rng, int(rng.integers(2, 8)),
                                    int(rng.integers(2, 6)))
        vals = check_identities(pi, do_laws)
        gap = max(abs(vals["contraction"] - vals["interventional"]),
                  abs(vals["interventional"] - vals["retrospective"]))
        max_gap = max(max_gap, gap)

    det_vals = []
    for _ in range(1_000):
        pi, do_laws = random_system(rng, 5, 4, deterministic=True)
        det_vals.append(check_identities(pi, do_laws)["interventional"])

    grid = gridworld_case()
    grid_gap = max(abs(grid["contraction"] - grid["interventional"]),
                   abs(grid["interventional"] - grid["retrospective"]))

    report = {
        "status": "collapse-bridge identity (Proposition B) verification",
        "random_systems": {"n": 10_000, "max_identity_gap": max_gap},
        "deterministic_boundary": {
            "n": 1_000,
            "max_action_attributable_collapse": float(max(det_vals)),
        },
        "gridworld_trigger_step": {**grid, "identity_gap": grid_gap},
        "pass": bool(max_gap < 1e-9 and max(det_vals) < 1e-12
                     and grid_gap < 1e-9),
        "reading": (
            "Action-attributable prospective contraction, pi-averaged "
            "interventional divergence and expected retrospective update "
            "are one quantity (I(A;B)) whenever the rollout law is fixed "
            "and the trigger is identifiable (MDP no-confounding); "
            "deterministic policies have zero action-attributable "
            "collapse, so ordinary information revelation is separated "
            "from system-driven collapse by construction."
        ),
    }
    out = OUTPUTS / "bridge_identity_verification.json"
    out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps({k: v for k, v in report.items() if k != "reading"},
                     indent=2))
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
